matrix:
  include:
    - language: csharp
      solution: Kaisen.sln
      mono: none
      dotnet: 3.1.101

      services:
        - mysql

      before_install:
        - git config user.email "travis@build.bot" && git config user.name "Travis CI"

      install:
       - mysql -uroot -e 'CREATE DATABASE mysql_test;'
       - mysql -uroot < sql/create_mysql.sql

      script:
        - dotnet restore
        - dotnet build --configuration Release --no-restore
        - dotnet test --no-restore --verbosity normal
    - language: node_js
      node_js:
        - "12.16.1"

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      before_script:
        - npm install -g @angular/cli

      script:
        - cd Kaizen/ClientApp
        - npm install
        - npm run build build -- --prod
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
