matrix:
  include:
    - language: csharp
      sudo: false
      solution: Kaisen.sln
      mono: none
      dotnet: 5.0.100

      before_install:
        - bash ./install-mysql-8.0.sh
        - git config user.email "travis@build.bot" && git config user.name "Travis CI"

      install:
        - mysql -uroot -e 'CREATE DATABASE mysql_test;'
        - mysql -uroot < sql/create_mysql.sql
        - nvm --version
        - nvm install 14.x
        - node --version

      script:
        - dotnet restore
        - dotnet build --configuration Release --no-restore
        - dotnet test --no-restore --verbosity normal
    - language: node_js
      node_js:
        - "14.x"

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      before_script:
        - npm install -g @angular/cli

      script:
        - cd Kaizen/ClientApp
        - npm install
        - npm run build -- --prod
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
