matrix:
  include:
    - language: csharp
      solution: Kaisen.sln
      mono: none
      dotnet: 3.1.101

      services:
        - mysql

      before_install:
        - git config user.email "travis@build.bot" && git config user.name "Travis CI"

      install:
       - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS kaizen_test;'
       - mysql -uroot -e 'CREATE USER 'kaizen'@'localhost' IDENTIFIED BY 'kaizen' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0'
       - mysql -uroot -e 'GRANT USAGE ON * . * TO 'kaizen'@'localhost';'
       - mysql -uroot -e 'GRANT ALL PRIVILEGES ON `kaizen_test` . * TO 'kaizen'@'localhost' WITH GRANT OPTION;'
       - sudo service mysql restart

      script:
        - dotnet restore
        - dotnet build --configuration Release --no-restore
        - dotnet test --no-restore --verbosity normal
    - language: node_js
      node_js:
        - "12.16.1"

      before_script:
        - npm install -g @angular/cli

      script:
        - cd Kaizen/ClientApp
        - npm install
        - ng build --prod
