version: 2.1

orbs:
  win: circleci/windows@2.4.0
    docker:
      - image: circleci/mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: kaizen_test
  node: circleci/node@3.0.1

jobs:
  build:
    executor: win/default

    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet test --no-restore --verbosity normal

  build_angular:
    executor: node/default

    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/Kaizen/ClientApp
      - run:
          name: Building
          command: cd Kaizen/ClientApp && npm run build

workflows:
  build_app:
    jobs:
      - build
      - build_angular
