name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: Set up MySQL 8
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: kaizen_test
          mysql user: kaizen
          mysql password: kaizen
      - name: Check MySQL version
        run: |
          mysql -h127.0.0.1 -uroot -proot -e 'SELECT version();'
          mysql -h127.0.0.1 -uroot -proot < sql/create_mysql.sql
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
